version: 2.1

# define this file as the setup phase of your dynamic configuration
setup: false

always: &always
  tags:
    only: /.*/
  branches:
    only: /.*/

main-master-release-branch-tag: &main-master-release-branch-tag
  tags:
    only: /.*/
  branches:
    only:
      - main
      - master
      - /release.*/
      - /circleci.*/

docker-context: &docker-context
  - prj-product-d-kannika-3bcd-artifact-registry-d-kannika-docker-internal
  - product-pool-gcp-oidc
  - prj-product-d-kannika-3bcd
  - slack-auth-token
  - dependency-tracker-api-key

cache-context: &cache-context
  - prj-product-d-kannika-3bcd-artifact-registry-d-kannika-docker-internal
  - prj-product-d-kannika-3bcd-artifact-registry-d-kannika-docker-internal-cache-cache
  - product-pool-gcp-oidc
  - prj-product-d-kannika-3bcd
  - slack-auth-token

# define the parameters that will be used to generate the dynamic configuration.
parameters:
  arm:
    type: boolean
    default: true
  push:
    type: boolean
    default: true
  tag:
    type: string
    default: "$CIRCLE_SHA1"

# invoke the orbs to filter, pack and continue configs.
orbs:
  orbert-downey-jr: cymo-eu/orbert-downey-jr@2.3.1

workflows:
  build:
    jobs:
      # =================
      # AMD build artifact
      - orbert-downey-jr/docker_buildx:
          filters: *always
          executor: orbert-downey-jr/ubuntu_2204_medium
          name: docker_build_amd
          image: kannika-bridge-cli
          image_tag: <<pipeline.number>>-amd64
          directory: .
          dockerfile: Dockerfile
          use_docker_buildkit: true
          extra_build_args: --ssh default
          # git_pull_submodules: true
          push_gar: << pipeline.parameters.push >>
          cache: $CIRCLE_BRANCH #if invoked by tag var is empty and cache will be disabled
          cache_key: $CIRCLE_BRANCH/amd
          cache_repo: $CACHE_ARTIFACT_REGISTRY_URL/$CACHE_ARTIFACT_REGISTRY_PROJECT/$CACHE_ARTIFACT_REGISTRY_NAME
          persist_to_workspace: true
          context: *cache-context
      # =================
      # ARM build artifact
      - orbert-downey-jr/docker_buildx:
          filters: *always
          executor: orbert-downey-jr/ubuntu_2204_medium_arm
          name: docker_build_arm
          image: kannika-bridge-cli
          image_tag: <<pipeline.number>>-arm64
          directory: .
          dockerfile: Dockerfile
          use_docker_buildkit: true
          extra_build_args: --ssh default
          # git_pull_submodules: true
          push_gar: << pipeline.parameters.push >>
          cache: $CIRCLE_BRANCH #if invoked by tag var is empty and cache will be disabled
          cache_key: $CIRCLE_BRANCH/arm
          cache_repo: $CACHE_ARTIFACT_REGISTRY_URL/$CACHE_ARTIFACT_REGISTRY_PROJECT/$CACHE_ARTIFACT_REGISTRY_NAME
          enabled: << pipeline.parameters.arm >>
          persist_to_workspace: true
          context: *cache-context
      # =================
      # manifest
      # create docker manifest and push images/manifest
      - orbert-downey-jr/docker_create_manifest_gar:
          filters: *main-master-release-branch-tag
          image_name: kannika-bridge-cli
          manifest_version: <<pipeline.number>>-manifest
          context: *docker-context
          requires:
            - docker_build_amd
            - docker_build_arm
      # Tag pushed manifest in gar with $CIRCLE_SHA1 or $CIRCLE_TAG
      - orbert-downey-jr/docker_tag_gar:
          filters: *main-master-release-branch-tag
          name: tag_with_sha
          image_name: kannika-bridge-cli
          image_old_tag: <<pipeline.number>>-manifest
          image_new_tag: << pipeline.parameters.tag >>
          requires:
            - orbert-downey-jr/docker_create_manifest_gar
          context: *docker-context
      # Tag pushed manifest in gar with 0.0.0
      - orbert-downey-jr/docker_tag_gar:
          filters: *main-master-release-branch-tag
          name: tag_with_0.0.0
          image_name: kannika-bridge-cli
          image_old_tag: <<pipeline.number>>-manifest
          image_new_tag: 0.0.0
          requires:
            - orbert-downey-jr/docker_create_manifest_gar
          context: *docker-context
      # =================
      # sbom
      # build sbom for rust code
      - orbert-downey-jr/rust_sbom:
          filters: *main-master-release-branch-tag
          path: .
          push_sbom_directly: false
          context:
            - slack-auth-token
            - dependency-tracker-api-key
      # merge rust sbom folder
      - orbert-downey-jr/cyclonedx_merge_folder:
          filters: *main-master-release-branch-tag
          requires:
            - orbert-downey-jr/rust_sbom
          context:
            - slack-auth-token
      # build sbom for rust container
      - orbert-downey-jr/syft_sbom:
          filters: *main-master-release-branch-tag
          pre-steps: # steps to run before steps defined in the job bar
            - orbert-downey-jr/gcp_auth_oidc:
                version: 471.0.0
            - orbert-downey-jr/gcp_ar_cred_help:
                registry_url: $ARTIFACT_REGISTRY_URL
          container_image_name: $ARTIFACT_REGISTRY_URL/$ARTIFACT_REGISTRY_PROJECT/$ARTIFACT_REGISTRY_NAME/kannika-bridge-cli
          container_image_tag: 0.0.0
          push_sbom_directly: false
          requires:
            - tag_with_0.0.0
          context: *docker-context
      # merge container sbom with code sbom
      - orbert-downey-jr/cyclonedx_merge:
          filters: *main-master-release-branch-tag
          requires:
            - orbert-downey-jr/syft_sbom
            - orbert-downey-jr/cyclonedx_merge_folder
          context:
            - slack-auth-token
      # push sbom to deptrack
      - orbert-downey-jr/push_sbom:
          filters: *main-master-release-branch-tag
          dt_project_name: kannika-bridge-cli
          dt_project_version: latest
          requires:
            - orbert-downey-jr/cyclonedx_merge
          context:
            - slack-auth-token
            - dependency-tracker-api-key
