[package]
name = "bridge-cli"
version.workspace = true
authors.workspace = true
description.workspace = true
edition.workspace = true

[dependencies]
bridge-core = { path = "../bridge-core" }

log = { workspace = true }
tokio = { workspace = true }
thiserror = { workspace = true }
env_logger = { workspace = true }
clap = { version = "4.5.48", features = ["derive"] }
inquire = "0.9.1"
comfy-table = "7.2.1"

[target.'cfg(windows)'.dependencies]
rdkafka = { version = "0.38.0", features = ["ssl", "gssapi", "sasl", "cmake-build"] }
