[package]
name = "bridge-core"
version.workspace = true
authors.workspace = true
description.workspace = true
edition.workspace = true

[dependencies]
rdkafka = { git = "https://github.com/j-santander/rust-rdkafka.git", commit = "ffe40196781087d3b5a311cca166805eb37f8090", features = ["ssl", "gssapi", "sasl"] }
log = { workspace = true }
thiserror = { workspace = true }
csv = { workspace = true }
serde = { version = "1.0.228", features = ["derive"] }

[target.'cfg(windows)'.dependencies]
rdkafka = { git = "https://github.com/j-santander/rust-rdkafka.git", commit = "ffe40196781087d3b5a311cca166805eb37f8090", features = ["ssl", "gssapi", "sasl", "cmake-build"] }

[dev-dependencies]
anyhow = "1.0.100"
assert_matches = "1.5.0"
tempfile = "3.23.0"
env_logger = { workspace = true }
tokio = { workspace = true }
